server:
  port: 8080

spring:
  application:
    name: device-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: device-service-group
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

aws:
  dynamodb:
    endpoint: http://localhost:4566
    region: eu-west-1