apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-device-service
  namespace: iot-security
spec:
  selector:
    app: device-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}