replicaCount: 2

image:
  repository: iot-security-device-service
  tag: "1.0.0-SNAPSHOT"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

env:
  KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  DYNAMODB_ENDPOINT: ${DYNAMODB_ENDPOINT:http://localhost:8000}
  AWS_REGION: "eu-west-1"

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10