apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-service
  namespace: iot-security
  labels:
    app: device-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: device-service
  template:
    metadata:
      labels:
        app: device-service
    spec:
      containers:
        - name: device-service
          image: iot-security-device-service:1.0.0-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
            - name: DYNAMODB_ENDPOINT
              value: ${DYNAMODB_ENDPOINT:http://localhost:8000}
            - name: AWS_REGION
              value: "eu-west-1"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10